### PR TITLE
[SYCL][Graph] Fix host task regression

### PR DESCRIPTION
**Pull request by reble**
Introduced by https://github.com/reble/llvm/pull/226

### CODE REVIEW

**Review by EwanC — CHANGES_REQUESTED** [review]
I'm seeing this fail to build

```
/home/ewan/Development/dpcpp/sycl/unittests/scheduler/Regression.cpp: In member function ‘virtual void SchedulerTest_CheckArgsBlobInPiEnqueueNativeKernelIsValid_Test::TestBody()’:
/home/ewan/Development/dpcpp/sycl/unittests/scheduler/Regression.cpp:84:31: error: no matching function for call to ‘sycl::_V1::detail::CGExecKernel::CGExecKernel(std::tuple_element<0, std::tuple<sycl::_V1::detail::NDRDescT, sycl::_V1::detail::AccessorImplHost> >::type&, std::shared_ptr<sycl::_V1::detail::HostKernel<SchedulerTest_CheckArgsBlobInPiEnqueueNativeKernelIsValid_Test::TestBody()::<lambda()>, void, 1> >, std::nullptr_t, std::nullptr_t, std::remove_reference<sycl::_V1::detail::CG::StorageInitHelper&>::type, <brace-enclosed initializer list>, const char [1], <brace-enclosed initializer list>, <brace-enclosed initializer list>, sycl::_V1::detail::CG::CGTYPE, <brace-enclosed initializer list>)’
   84 |       /*KernelCacheConfig*/ {})};
      |                               ^
```

I think the ` detail::CGExecKernel` constructor at https://github.com/reble/llvm/blob/sycl-graph-release-patch1/sycl/include/sycl/detail/cg.hpp#L172 needs to be updated to take a shared_ptr rather than unique_ptr on construction, which makes sense as a change we should make.

I've rolled this all up into PR https://github.com/reble/llvm/pull/228/ which has another scheduler fix.

**Comment by EwanC** [comment]
Closing as superseded by PR #228
